resolver: lts-11.2

packages:
- '.'
- location:
    git: https://github.com/avieth/hackage-db
    commit: 9da3fb02f09e675d9fbb8138ad6c38091ce11268
  extra-dep: true
- location:
    git: https://github.com/avieth/cabal2nix
    commit: 90ec7a808148d6e52512b92b044ced8b704cb7f9
  extra-dep: true

extra-deps:
- Cabal-2.2.0.1
- distribution-nixpkgs-1.1.1
- stack-1.7.1
- rio-0.1.2.0

allow-newer: true

flags: {}

nix:
  packages: [zlib,gmp,git,pcre,openssl]

extra-package-dbs: []

ghc-options:
  stack2nix: -Werror
