resolver: lts-11.2

packages:
- '.'
- location:
    git: https://github.com/avieth/hackage-db
    commit: 9da3fb02f09e675d9fbb8138ad6c38091ce11268
  extra-dep: true
- location:
    git: https://github.com/avieth/cabal2nix
    commit: 90ec7a808148d6e52512b92b044ced8b704cb7f9
  extra-dep: true

extra-deps:
- Cabal-2.2.0.1
- distribution-nixpkgs-1.1.1
- stack-1.7.1
- extra-1.6.6
- hackage-security-0.5.3.0
- hpack-0.28.2
- http-api-data-0.3.8.1
- http-client-0.5.12.1
- http-conduit-2.3.1
- monad-logger-0.3.28.5
- persistent-2.8.2
- resourcet-1.2.1
- rio-0.1.2.0
- unicode-transforms-0.3.4
- yaml-0.8.30

flags: {}

nix:
  packages: [zlib,gmp,git,pcre,openssl]

extra-package-dbs: []

ghc-options:
  stack2nix: -Werror
